language: go
go:
    - 1.9.x
    - 1.10.x
install:
    - go get -d -v .
    - (cd $GOPATH/src/github.com/bwmarrin/discordgo; git checkout develop)
    - go get -v github.com/golang/lint/golint
script:
    - go install ./
    - diff <(gofmt -d .) <(echo -n)
    - go vet -x ./...
    - golint -set_exit_status ./...
